/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class acswigPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("acswig", EntryPoint="SWIGRegisterExceptionCallbacks_acswig")]
    public static extern void SWIGRegisterExceptionCallbacks_acswig(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("acswig", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_acswig")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_acswig(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_acswig(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_acswig(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(acswigPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(acswigPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("acswig", EntryPoint="SWIGRegisterStringCallback_acswig")]
    public static extern void SWIGRegisterStringCallback_acswig(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_acswig(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static acswigPINVOKE() {
  }


  [DllImport("acswig", EntryPoint="CSharp_COLORCONV_KEEP_TRANS_get")]
  public static extern int COLORCONV_KEEP_TRANS_get();

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_w_set")]
  public static extern void BITMAP_w_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_w_get")]
  public static extern int BITMAP_w_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_h_set")]
  public static extern void BITMAP_h_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_h_get")]
  public static extern int BITMAP_h_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_clip_set")]
  public static extern void BITMAP_clip_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_clip_get")]
  public static extern int BITMAP_clip_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cl_set")]
  public static extern void BITMAP_cl_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cl_get")]
  public static extern int BITMAP_cl_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cr_set")]
  public static extern void BITMAP_cr_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cr_get")]
  public static extern int BITMAP_cr_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_ct_set")]
  public static extern void BITMAP_ct_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_ct_get")]
  public static extern int BITMAP_ct_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cb_set")]
  public static extern void BITMAP_cb_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_cb_get")]
  public static extern int BITMAP_cb_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_vtable_set")]
  public static extern void BITMAP_vtable_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_vtable_get")]
  public static extern IntPtr BITMAP_vtable_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_id_set")]
  public static extern void BITMAP_id_set(HandleRef jarg1, uint jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_id_get")]
  public static extern uint BITMAP_id_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_x_ofs_set")]
  public static extern void BITMAP_x_ofs_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_x_ofs_get")]
  public static extern int BITMAP_x_ofs_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_y_ofs_set")]
  public static extern void BITMAP_y_ofs_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_y_ofs_get")]
  public static extern int BITMAP_y_ofs_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_seg_set")]
  public static extern void BITMAP_seg_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_seg_get")]
  public static extern int BITMAP_seg_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_line_set")]
  public static extern void BITMAP_line_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_line_get")]
  public static extern IntPtr BITMAP_line_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_BITMAP_GetLine")]
  public static extern IntPtr BITMAP_GetLine(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_new_BITMAP")]
  public static extern IntPtr new_BITMAP();

  [DllImport("acswig", EntryPoint="CSharp_delete_BITMAP")]
  public static extern void delete_BITMAP(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RGB_r_set")]
  public static extern void RGB_r_set(HandleRef jarg1, byte jarg2);

  [DllImport("acswig", EntryPoint="CSharp_RGB_r_get")]
  public static extern byte RGB_r_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RGB_g_set")]
  public static extern void RGB_g_set(HandleRef jarg1, byte jarg2);

  [DllImport("acswig", EntryPoint="CSharp_RGB_g_get")]
  public static extern byte RGB_g_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RGB_b_set")]
  public static extern void RGB_b_set(HandleRef jarg1, byte jarg2);

  [DllImport("acswig", EntryPoint="CSharp_RGB_b_get")]
  public static extern byte RGB_b_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RGB_filler_set")]
  public static extern void RGB_filler_set(HandleRef jarg1, byte jarg2);

  [DllImport("acswig", EntryPoint="CSharp_RGB_filler_get")]
  public static extern byte RGB_filler_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_new_RGB")]
  public static extern IntPtr new_RGB();

  [DllImport("acswig", EntryPoint="CSharp_delete_RGB")]
  public static extern void delete_RGB(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_PAL_SIZE_get")]
  public static extern int PAL_SIZE_get();

  [DllImport("acswig", EntryPoint="CSharp_allegro_set_palette")]
  public static extern void allegro_set_palette(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_destroy_bitmap")]
  public static extern void destroy_bitmap(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_create_bitmap_ex")]
  public static extern IntPtr create_bitmap_ex(int jarg1, int jarg2, int jarg3);

  [DllImport("acswig", EntryPoint="CSharp_abuf_set")]
  public static extern void abuf_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_abuf_get")]
  public static extern IntPtr abuf_get();

  [DllImport("acswig", EntryPoint="CSharp_blit")]
  public static extern void blit(HandleRef jarg1, HandleRef jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);

  [DllImport("acswig", EntryPoint="CSharp_new_RgbArray")]
  public static extern IntPtr new_RgbArray(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_delete_RgbArray")]
  public static extern void delete_RgbArray(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RgbArray_getitem")]
  public static extern IntPtr RgbArray_getitem(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_RgbArray_setitem")]
  public static extern void RgbArray_setitem(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("acswig", EntryPoint="CSharp_RgbArray_cast")]
  public static extern IntPtr RgbArray_cast(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_RgbArray_frompointer")]
  public static extern IntPtr RgbArray_frompointer(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_select_palette")]
  public static extern void select_palette(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_unselect_palette")]
  public static extern void unselect_palette();

  [DllImport("acswig", EntryPoint="CSharp_set_color_conversion")]
  public static extern void set_color_conversion(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_get_color_conversion")]
  public static extern int get_color_conversion();

  [DllImport("acswig", EntryPoint="CSharp_bitmap_color_depth")]
  public static extern int bitmap_color_depth(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_SIMP_INDEX0_get")]
  public static extern int SIMP_INDEX0_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_TOPLEFT_get")]
  public static extern int SIMP_TOPLEFT_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_BOTLEFT_get")]
  public static extern int SIMP_BOTLEFT_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_TOPRIGHT_get")]
  public static extern int SIMP_TOPRIGHT_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_BOTRIGHT_get")]
  public static extern int SIMP_BOTRIGHT_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_LEAVEALONE_get")]
  public static extern int SIMP_LEAVEALONE_get();

  [DllImport("acswig", EntryPoint="CSharp_SIMP_NONE_get")]
  public static extern int SIMP_NONE_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_INIT_SPR_get")]
  public static extern int MAX_INIT_SPR_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_OBJ_get")]
  public static extern int MAX_OBJ_get();

  [DllImport("acswig", EntryPoint="CSharp_NUM_MISC_get")]
  public static extern int NUM_MISC_get();

  [DllImport("acswig", EntryPoint="CSharp_MAXMESS_get")]
  public static extern int MAXMESS_get();

  [DllImport("acswig", EntryPoint="CSharp_NUMOTCON_get")]
  public static extern int NUMOTCON_get();

  [DllImport("acswig", EntryPoint="CSharp_NUM_CONDIT_get")]
  public static extern int NUM_CONDIT_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_HOTSPOTS_get")]
  public static extern int MAX_HOTSPOTS_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_REGIONS_get")]
  public static extern int MAX_REGIONS_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_SCRIPT_NAME_LEN_get")]
  public static extern int MAX_SCRIPT_NAME_LEN_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_WALK_AREAS_get")]
  public static extern int MAX_WALK_AREAS_get();

  [DllImport("acswig", EntryPoint="CSharp_MAXPOINTS_get")]
  public static extern int MAXPOINTS_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_SPRITES_get")]
  public static extern int MAX_SPRITES_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_CURSOR_get")]
  public static extern int MAX_CURSOR_get();

  [DllImport("acswig", EntryPoint="CSharp_PAL_GAMEWIDE_get")]
  public static extern int PAL_GAMEWIDE_get();

  [DllImport("acswig", EntryPoint="CSharp_PAL_LOCKED_get")]
  public static extern int PAL_LOCKED_get();

  [DllImport("acswig", EntryPoint="CSharp_PAL_BACKGROUND_get")]
  public static extern int PAL_BACKGROUND_get();

  [DllImport("acswig", EntryPoint="CSharp_MAXGLOBALMES_get")]
  public static extern int MAXGLOBALMES_get();

  [DllImport("acswig", EntryPoint="CSharp_MAXLANGUAGE_get")]
  public static extern int MAXLANGUAGE_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_FONTS_get")]
  public static extern int MAX_FONTS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DEBUGMODE_get")]
  public static extern int OPT_DEBUGMODE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_SCORESOUND_get")]
  public static extern int OPT_SCORESOUND_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_WALKONLOOK_get")]
  public static extern int OPT_WALKONLOOK_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DIALOGIFACE_get")]
  public static extern int OPT_DIALOGIFACE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_ANTIGLIDE_get")]
  public static extern int OPT_ANTIGLIDE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_TWCUSTOM_get")]
  public static extern int OPT_TWCUSTOM_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DIALOGGAP_get")]
  public static extern int OPT_DIALOGGAP_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NOSKIPTEXT_get")]
  public static extern int OPT_NOSKIPTEXT_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DISABLEOFF_get")]
  public static extern int OPT_DISABLEOFF_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_ALWAYSSPCH_get")]
  public static extern int OPT_ALWAYSSPCH_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_SPEECHTYPE_get")]
  public static extern int OPT_SPEECHTYPE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_PIXPERFECT_get")]
  public static extern int OPT_PIXPERFECT_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NOWALKMODE_get")]
  public static extern int OPT_NOWALKMODE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_LETTERBOX_get")]
  public static extern int OPT_LETTERBOX_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_FIXEDINVCURSOR_get")]
  public static extern int OPT_FIXEDINVCURSOR_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NOLOSEINV_get")]
  public static extern int OPT_NOLOSEINV_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NOSCALEFNT_get")]
  public static extern int OPT_NOSCALEFNT_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_SPLITRESOURCES_get")]
  public static extern int OPT_SPLITRESOURCES_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_ROTATECHARS_get")]
  public static extern int OPT_ROTATECHARS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_FADETYPE_get")]
  public static extern int OPT_FADETYPE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_HANDLEINVCLICKS_get")]
  public static extern int OPT_HANDLEINVCLICKS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_MOUSEWHEEL_get")]
  public static extern int OPT_MOUSEWHEEL_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DIALOGNUMBERED_get")]
  public static extern int OPT_DIALOGNUMBERED_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DIALOGUPWARDS_get")]
  public static extern int OPT_DIALOGUPWARDS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_CROSSFADEMUSIC_get")]
  public static extern int OPT_CROSSFADEMUSIC_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_ANTIALIASFONTS_get")]
  public static extern int OPT_ANTIALIASFONTS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_THOUGHTGUI_get")]
  public static extern int OPT_THOUGHTGUI_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_TURNTOFACELOC_get")]
  public static extern int OPT_TURNTOFACELOC_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_RIGHTLEFTWRITE_get")]
  public static extern int OPT_RIGHTLEFTWRITE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_DUPLICATEINV_get")]
  public static extern int OPT_DUPLICATEINV_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_SAVESCREENSHOT_get")]
  public static extern int OPT_SAVESCREENSHOT_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_PORTRAITSIDE_get")]
  public static extern int OPT_PORTRAITSIDE_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_STRICTSCRIPTING_get")]
  public static extern int OPT_STRICTSCRIPTING_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_LEFTTORIGHTEVAL_get")]
  public static extern int OPT_LEFTTORIGHTEVAL_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_COMPRESSSPRITES_get")]
  public static extern int OPT_COMPRESSSPRITES_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_STRICTSTRINGS_get")]
  public static extern int OPT_STRICTSTRINGS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NEWGUIALPHA_get")]
  public static extern int OPT_NEWGUIALPHA_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_RUNGAMEDLGOPTS_get")]
  public static extern int OPT_RUNGAMEDLGOPTS_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NATIVECOORDINATES_get")]
  public static extern int OPT_NATIVECOORDINATES_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_OLDTALKANIMSPD_get")]
  public static extern int OPT_OLDTALKANIMSPD_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_HIGHESTOPTION_get")]
  public static extern int OPT_HIGHESTOPTION_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_NOMODMUSIC_get")]
  public static extern int OPT_NOMODMUSIC_get();

  [DllImport("acswig", EntryPoint="CSharp_OPT_LIPSYNCTEXT_get")]
  public static extern int OPT_LIPSYNCTEXT_get();

  [DllImport("acswig", EntryPoint="CSharp_PORTRAIT_LEFT_get")]
  public static extern int PORTRAIT_LEFT_get();

  [DllImport("acswig", EntryPoint="CSharp_PORTRAIT_RIGHT_get")]
  public static extern int PORTRAIT_RIGHT_get();

  [DllImport("acswig", EntryPoint="CSharp_PORTRAIT_ALTERNATE_get")]
  public static extern int PORTRAIT_ALTERNATE_get();

  [DllImport("acswig", EntryPoint="CSharp_PORTRAIT_XPOSITION_get")]
  public static extern int PORTRAIT_XPOSITION_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_NORMAL_get")]
  public static extern int FADE_NORMAL_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_INSTANT_get")]
  public static extern int FADE_INSTANT_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_DISSOLVE_get")]
  public static extern int FADE_DISSOLVE_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_BOXOUT_get")]
  public static extern int FADE_BOXOUT_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_CROSSFADE_get")]
  public static extern int FADE_CROSSFADE_get();

  [DllImport("acswig", EntryPoint="CSharp_FADE_LAST_get")]
  public static extern int FADE_LAST_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_640x400_get")]
  public static extern int SPF_640x400_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_HICOLOR_get")]
  public static extern int SPF_HICOLOR_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_DYNAMICALLOC_get")]
  public static extern int SPF_DYNAMICALLOC_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_TRUECOLOR_get")]
  public static extern int SPF_TRUECOLOR_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_ALPHACHANNEL_get")]
  public static extern int SPF_ALPHACHANNEL_get();

  [DllImport("acswig", EntryPoint="CSharp_SPF_HADALPHACHANNEL_get")]
  public static extern int SPF_HADALPHACHANNEL_get();

  [DllImport("acswig", EntryPoint="CSharp_FFLG_SIZEMASK_get")]
  public static extern int FFLG_SIZEMASK_get();

  [DllImport("acswig", EntryPoint="CSharp_FONT_OUTLINE_AUTO_get")]
  public static extern int FONT_OUTLINE_AUTO_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_FONT_SIZE_get")]
  public static extern int MAX_FONT_SIZE_get();

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_gamename_set")]
  public static extern void GameSetupStructBase_gamename_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_gamename_get")]
  public static extern string GameSetupStructBase_gamename_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_options_set")]
  public static extern void GameSetupStructBase_options_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_options_get")]
  public static extern IntPtr GameSetupStructBase_options_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_paluses_set")]
  public static extern void GameSetupStructBase_paluses_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_paluses_get")]
  public static extern IntPtr GameSetupStructBase_paluses_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_defpal_set")]
  public static extern void GameSetupStructBase_defpal_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_defpal_get")]
  public static extern IntPtr GameSetupStructBase_defpal_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numviews_set")]
  public static extern void GameSetupStructBase_numviews_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numviews_get")]
  public static extern int GameSetupStructBase_numviews_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numcharacters_set")]
  public static extern void GameSetupStructBase_numcharacters_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numcharacters_get")]
  public static extern int GameSetupStructBase_numcharacters_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_playercharacter_set")]
  public static extern void GameSetupStructBase_playercharacter_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_playercharacter_get")]
  public static extern int GameSetupStructBase_playercharacter_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_totalscore_set")]
  public static extern void GameSetupStructBase_totalscore_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_totalscore_get")]
  public static extern int GameSetupStructBase_totalscore_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numinvitems_set")]
  public static extern void GameSetupStructBase_numinvitems_set(HandleRef jarg1, short jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numinvitems_get")]
  public static extern short GameSetupStructBase_numinvitems_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numdialog_set")]
  public static extern void GameSetupStructBase_numdialog_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numdialog_get")]
  public static extern int GameSetupStructBase_numdialog_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numdlgmessage_set")]
  public static extern void GameSetupStructBase_numdlgmessage_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numdlgmessage_get")]
  public static extern int GameSetupStructBase_numdlgmessage_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numfonts_set")]
  public static extern void GameSetupStructBase_numfonts_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numfonts_get")]
  public static extern int GameSetupStructBase_numfonts_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_color_depth_set")]
  public static extern void GameSetupStructBase_color_depth_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_color_depth_get")]
  public static extern int GameSetupStructBase_color_depth_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_target_win_set")]
  public static extern void GameSetupStructBase_target_win_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_target_win_get")]
  public static extern int GameSetupStructBase_target_win_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_dialog_bullet_set")]
  public static extern void GameSetupStructBase_dialog_bullet_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_dialog_bullet_get")]
  public static extern int GameSetupStructBase_dialog_bullet_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_hotdot_set")]
  public static extern void GameSetupStructBase_hotdot_set(HandleRef jarg1, ushort jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_hotdot_get")]
  public static extern ushort GameSetupStructBase_hotdot_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_hotdotouter_set")]
  public static extern void GameSetupStructBase_hotdotouter_set(HandleRef jarg1, ushort jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_hotdotouter_get")]
  public static extern ushort GameSetupStructBase_hotdotouter_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_uniqueid_set")]
  public static extern void GameSetupStructBase_uniqueid_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_uniqueid_get")]
  public static extern int GameSetupStructBase_uniqueid_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numgui_set")]
  public static extern void GameSetupStructBase_numgui_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numgui_get")]
  public static extern int GameSetupStructBase_numgui_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numcursors_set")]
  public static extern void GameSetupStructBase_numcursors_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_numcursors_get")]
  public static extern int GameSetupStructBase_numcursors_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_default_resolution_set")]
  public static extern void GameSetupStructBase_default_resolution_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_default_resolution_get")]
  public static extern int GameSetupStructBase_default_resolution_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_default_lipsync_frame_set")]
  public static extern void GameSetupStructBase_default_lipsync_frame_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_default_lipsync_frame_get")]
  public static extern int GameSetupStructBase_default_lipsync_frame_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_invhotdotsprite_set")]
  public static extern void GameSetupStructBase_invhotdotsprite_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_invhotdotsprite_get")]
  public static extern int GameSetupStructBase_invhotdotsprite_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_reserved_set")]
  public static extern void GameSetupStructBase_reserved_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_reserved_get")]
  public static extern IntPtr GameSetupStructBase_reserved_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_messages_set")]
  public static extern void GameSetupStructBase_messages_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_messages_get")]
  public static extern IntPtr GameSetupStructBase_messages_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_dict_set")]
  public static extern void GameSetupStructBase_dict_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_dict_get")]
  public static extern IntPtr GameSetupStructBase_dict_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_globalscript_set")]
  public static extern void GameSetupStructBase_globalscript_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_globalscript_get")]
  public static extern string GameSetupStructBase_globalscript_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_chars_set")]
  public static extern void GameSetupStructBase_chars_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_chars_get")]
  public static extern IntPtr GameSetupStructBase_chars_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_compiled_script_set")]
  public static extern void GameSetupStructBase_compiled_script_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStructBase_compiled_script_get")]
  public static extern IntPtr GameSetupStructBase_compiled_script_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_new_GameSetupStructBase")]
  public static extern IntPtr new_GameSetupStructBase();

  [DllImport("acswig", EntryPoint="CSharp_delete_GameSetupStructBase")]
  public static extern void delete_GameSetupStructBase(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_MAXVIEWNAMELENGTH_get")]
  public static extern int MAXVIEWNAMELENGTH_get();

  [DllImport("acswig", EntryPoint="CSharp_MAXLIPSYNCFRAMES_get")]
  public static extern int MAXLIPSYNCFRAMES_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_GUID_LENGTH_get")]
  public static extern int MAX_GUID_LENGTH_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_SG_EXT_LENGTH_get")]
  public static extern int MAX_SG_EXT_LENGTH_get();

  [DllImport("acswig", EntryPoint="CSharp_MAX_SG_FOLDER_LEN_get")]
  public static extern int MAX_SG_FOLDER_LEN_get();

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_fontflags_set")]
  public static extern void GameSetupStruct_fontflags_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_fontflags_get")]
  public static extern IntPtr GameSetupStruct_fontflags_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_fontoutline_set")]
  public static extern void GameSetupStruct_fontoutline_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_fontoutline_get")]
  public static extern string GameSetupStruct_fontoutline_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_spriteflags_set")]
  public static extern void GameSetupStruct_spriteflags_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_spriteflags_get")]
  public static extern IntPtr GameSetupStruct_spriteflags_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invinfo_set")]
  public static extern void GameSetupStruct_invinfo_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invinfo_get")]
  public static extern IntPtr GameSetupStruct_invinfo_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_mcurs_set")]
  public static extern void GameSetupStruct_mcurs_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_mcurs_get")]
  public static extern IntPtr GameSetupStruct_mcurs_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_intrChar_set")]
  public static extern void GameSetupStruct_intrChar_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_intrChar_get")]
  public static extern IntPtr GameSetupStruct_intrChar_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_intrInv_set")]
  public static extern void GameSetupStruct_intrInv_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_intrInv_get")]
  public static extern IntPtr GameSetupStruct_intrInv_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_charScripts_set")]
  public static extern void GameSetupStruct_charScripts_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_charScripts_get")]
  public static extern IntPtr GameSetupStruct_charScripts_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invScripts_set")]
  public static extern void GameSetupStruct_invScripts_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invScripts_get")]
  public static extern IntPtr GameSetupStruct_invScripts_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_filever_set")]
  public static extern void GameSetupStruct_filever_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_filever_get")]
  public static extern int GameSetupStruct_filever_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_lipSyncFrameLetters_set")]
  public static extern void GameSetupStruct_lipSyncFrameLetters_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_lipSyncFrameLetters_get")]
  public static extern IntPtr GameSetupStruct_lipSyncFrameLetters_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_propSchema_set")]
  public static extern void GameSetupStruct_propSchema_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_propSchema_get")]
  public static extern IntPtr GameSetupStruct_propSchema_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_charProps_set")]
  public static extern void GameSetupStruct_charProps_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_charProps_get")]
  public static extern IntPtr GameSetupStruct_charProps_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invProps_set")]
  public static extern void GameSetupStruct_invProps_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invProps_get")]
  public static extern IntPtr GameSetupStruct_invProps_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_viewNames_set")]
  public static extern void GameSetupStruct_viewNames_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_viewNames_get")]
  public static extern IntPtr GameSetupStruct_viewNames_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invScriptNames_set")]
  public static extern void GameSetupStruct_invScriptNames_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_invScriptNames_get")]
  public static extern IntPtr GameSetupStruct_invScriptNames_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_dialogScriptNames_set")]
  public static extern void GameSetupStruct_dialogScriptNames_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_dialogScriptNames_get")]
  public static extern IntPtr GameSetupStruct_dialogScriptNames_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_guid_set")]
  public static extern void GameSetupStruct_guid_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_guid_get")]
  public static extern string GameSetupStruct_guid_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_saveGameFileExtension_set")]
  public static extern void GameSetupStruct_saveGameFileExtension_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_saveGameFileExtension_get")]
  public static extern string GameSetupStruct_saveGameFileExtension_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_saveGameFolderName_set")]
  public static extern void GameSetupStruct_saveGameFolderName_set(HandleRef jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_saveGameFolderName_get")]
  public static extern string GameSetupStruct_saveGameFolderName_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomCount_set")]
  public static extern void GameSetupStruct_roomCount_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomCount_get")]
  public static extern int GameSetupStruct_roomCount_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomNumbers_set")]
  public static extern void GameSetupStruct_roomNumbers_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomNumbers_get")]
  public static extern IntPtr GameSetupStruct_roomNumbers_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomNames_set")]
  public static extern void GameSetupStruct_roomNames_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_roomNames_get")]
  public static extern IntPtr GameSetupStruct_roomNames_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipCount_set")]
  public static extern void GameSetupStruct_audioClipCount_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipCount_get")]
  public static extern int GameSetupStruct_audioClipCount_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClips_set")]
  public static extern void GameSetupStruct_audioClips_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClips_get")]
  public static extern IntPtr GameSetupStruct_audioClips_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipTypeCount_set")]
  public static extern void GameSetupStruct_audioClipTypeCount_set(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipTypeCount_get")]
  public static extern int GameSetupStruct_audioClipTypeCount_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipTypes_set")]
  public static extern void GameSetupStruct_audioClipTypes_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_audioClipTypes_get")]
  public static extern IntPtr GameSetupStruct_audioClipTypes_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_GetOption")]
  public static extern bool GameSetupStruct_GetOption(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_SetOption")]
  public static extern void GameSetupStruct_SetOption(HandleRef jarg1, int jarg2, bool jarg3);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_GetSpriteFlag")]
  public static extern byte GameSetupStruct_GetSpriteFlag(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_SetSpriteFlag")]
  public static extern void GameSetupStruct_SetSpriteFlag(HandleRef jarg1, int jarg2, byte jarg3);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_GetPalUse")]
  public static extern byte GameSetupStruct_GetPalUse(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_SetPalUse")]
  public static extern void GameSetupStruct_SetPalUse(HandleRef jarg1, int jarg2, byte jarg3);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_GetFontFlag")]
  public static extern byte GameSetupStruct_GetFontFlag(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_SetFontFlag")]
  public static extern void GameSetupStruct_SetFontFlag(HandleRef jarg1, int jarg2, byte jarg3);

  [DllImport("acswig", EntryPoint="CSharp_new_GameSetupStruct")]
  public static extern IntPtr new_GameSetupStruct();

  [DllImport("acswig", EntryPoint="CSharp_delete_GameSetupStruct")]
  public static extern void delete_GameSetupStruct(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_get_palette_entry")]
  public static extern IntPtr get_palette_entry(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_set_palette_entry")]
  public static extern void set_palette_entry(int jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_roomstruct_ebscene_set")]
  public static extern void roomstruct_ebscene_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_roomstruct_ebscene_get")]
  public static extern IntPtr roomstruct_ebscene_get(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_roomstruct_GetEbScene")]
  public static extern IntPtr roomstruct_GetEbScene(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_new_roomstruct")]
  public static extern IntPtr new_roomstruct();

  [DllImport("acswig", EntryPoint="CSharp_delete_roomstruct")]
  public static extern void delete_roomstruct(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_antiAliasFonts_set")]
  public static extern void antiAliasFonts_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_antiAliasFonts_get")]
  public static extern int antiAliasFonts_get();

  [DllImport("acswig", EntryPoint="CSharp_SAVEBUFFERSIZE_get")]
  public static extern int SAVEBUFFERSIZE_get();

  [DllImport("acswig", EntryPoint="CSharp_mousex_set")]
  public static extern void mousex_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_mousex_get")]
  public static extern int mousex_get();

  [DllImport("acswig", EntryPoint="CSharp_mousey_set")]
  public static extern void mousey_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_mousey_get")]
  public static extern int mousey_get();

  [DllImport("acswig", EntryPoint="CSharp_sxmult_set")]
  public static extern void sxmult_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_sxmult_get")]
  public static extern int sxmult_get();

  [DllImport("acswig", EntryPoint="CSharp_symult_set")]
  public static extern void symult_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_symult_get")]
  public static extern int symult_get();

  [DllImport("acswig", EntryPoint="CSharp_dsc_want_hires_set")]
  public static extern void dsc_want_hires_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_dsc_want_hires_get")]
  public static extern int dsc_want_hires_get();

  [DllImport("acswig", EntryPoint="CSharp_enable_greyed_out_masks_set")]
  public static extern void enable_greyed_out_masks_set(bool jarg1);

  [DllImport("acswig", EntryPoint="CSharp_enable_greyed_out_masks_get")]
  public static extern bool enable_greyed_out_masks_get();

  [DllImport("acswig", EntryPoint="CSharp_outlineGuiObjects_set")]
  public static extern void outlineGuiObjects_set(bool jarg1);

  [DllImport("acswig", EntryPoint="CSharp_outlineGuiObjects_get")]
  public static extern bool outlineGuiObjects_get();

  [DllImport("acswig", EntryPoint="CSharp_palette_set")]
  public static extern void palette_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_palette_get")]
  public static extern IntPtr palette_get();

  [DllImport("acswig", EntryPoint="CSharp_thisgame_set")]
  public static extern void thisgame_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_thisgame_get")]
  public static extern IntPtr thisgame_get();

  [DllImport("acswig", EntryPoint="CSharp_tempgui_set")]
  public static extern void tempgui_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_tempgui_get")]
  public static extern IntPtr tempgui_get();

  [DllImport("acswig", EntryPoint="CSharp_sprsetname_set")]
  public static extern void sprsetname_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_sprsetname_get")]
  public static extern string sprsetname_get();

  [DllImport("acswig", EntryPoint="CSharp_clibendsig_set")]
  public static extern void clibendsig_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_clibendsig_get")]
  public static extern string clibendsig_get();

  [DllImport("acswig", EntryPoint="CSharp_old_editor_data_file_set")]
  public static extern void old_editor_data_file_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_old_editor_data_file_get")]
  public static extern string old_editor_data_file_get();

  [DllImport("acswig", EntryPoint="CSharp_new_editor_data_file_set")]
  public static extern void new_editor_data_file_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_new_editor_data_file_get")]
  public static extern string new_editor_data_file_get();

  [DllImport("acswig", EntryPoint="CSharp_old_editor_main_game_file_set")]
  public static extern void old_editor_main_game_file_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_old_editor_main_game_file_get")]
  public static extern string old_editor_main_game_file_get();

  [DllImport("acswig", EntryPoint="CSharp_TEMPLATE_LOCK_FILE_set")]
  public static extern void TEMPLATE_LOCK_FILE_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_TEMPLATE_LOCK_FILE_get")]
  public static extern string TEMPLATE_LOCK_FILE_get();

  [DllImport("acswig", EntryPoint="CSharp_ROOM_TEMPLATE_ID_FILE_set")]
  public static extern void ROOM_TEMPLATE_ID_FILE_set(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_ROOM_TEMPLATE_ID_FILE_get")]
  public static extern string ROOM_TEMPLATE_ID_FILE_get();

  [DllImport("acswig", EntryPoint="CSharp_spritesModified_set")]
  public static extern void spritesModified_set(bool jarg1);

  [DllImport("acswig", EntryPoint="CSharp_spritesModified_get")]
  public static extern bool spritesModified_get();

  [DllImport("acswig", EntryPoint="CSharp_thisroom_set")]
  public static extern void thisroom_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_thisroom_get")]
  public static extern IntPtr thisroom_get();

  [DllImport("acswig", EntryPoint="CSharp_roomModified_set")]
  public static extern void roomModified_set(bool jarg1);

  [DllImport("acswig", EntryPoint="CSharp_roomModified_get")]
  public static extern bool roomModified_get();

  [DllImport("acswig", EntryPoint="CSharp_drawBuffer_set")]
  public static extern void drawBuffer_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_drawBuffer_get")]
  public static extern IntPtr drawBuffer_get();

  [DllImport("acswig", EntryPoint="CSharp_undoBuffer_set")]
  public static extern void undoBuffer_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_undoBuffer_get")]
  public static extern IntPtr undoBuffer_get();

  [DllImport("acswig", EntryPoint="CSharp_loaded_room_number_set")]
  public static extern void loaded_room_number_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_loaded_room_number_get")]
  public static extern int loaded_room_number_get();

  [DllImport("acswig", EntryPoint="CSharp_numScriptModules_set")]
  public static extern void numScriptModules_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_numScriptModules_get")]
  public static extern int numScriptModules_get();

  [DllImport("acswig", EntryPoint="CSharp_scModules_set")]
  public static extern void scModules_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_scModules_get")]
  public static extern IntPtr scModules_get();

  [DllImport("acswig", EntryPoint="CSharp_dialog_set")]
  public static extern void dialog_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_dialog_get")]
  public static extern IntPtr dialog_get();

  [DllImport("acswig", EntryPoint="CSharp_dlgscript_set")]
  public static extern void dlgscript_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_dlgscript_get")]
  public static extern IntPtr dlgscript_get();

  [DllImport("acswig", EntryPoint="CSharp_guis_set")]
  public static extern void guis_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_guis_get")]
  public static extern IntPtr guis_get();

  [DllImport("acswig", EntryPoint="CSharp_oldViews_set")]
  public static extern void oldViews_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_oldViews_get")]
  public static extern IntPtr oldViews_get();

  [DllImport("acswig", EntryPoint="CSharp_newViews_set")]
  public static extern void newViews_set(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_newViews_get")]
  public static extern IntPtr newViews_get();

  [DllImport("acswig", EntryPoint="CSharp_numNewViews_set")]
  public static extern void numNewViews_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_numNewViews_get")]
  public static extern int numNewViews_get();

  [DllImport("acswig", EntryPoint="CSharp_clibfopen")]
  public static extern IntPtr clibfopen(string jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_csetlib")]
  public static extern int csetlib(string jarg1, string jarg2);

  [DllImport("acswig", EntryPoint="CSharp_clibGetNumFiles")]
  public static extern int clibGetNumFiles();

  [DllImport("acswig", EntryPoint="CSharp_clibGetFileName")]
  public static extern string clibGetFileName(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_clibgetoriginalfilename")]
  public static extern string clibgetoriginalfilename();

  [DllImport("acswig", EntryPoint="CSharp_cfopenpriority_set")]
  public static extern void cfopenpriority_set(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_cfopenpriority_get")]
  public static extern int cfopenpriority_get();

  [DllImport("acswig", EntryPoint="CSharp_Scintilla_RegisterClasses")]
  public static extern bool Scintilla_RegisterClasses(IntPtr jarg1);

  [DllImport("acswig", EntryPoint="CSharp_Scintilla_LinkLexers")]
  public static extern int Scintilla_LinkLexers();

  [DllImport("acswig", EntryPoint="CSharp_ShouldAntiAliasText")]
  public static extern bool ShouldAntiAliasText();

  [DllImport("acswig", EntryPoint="CSharp_serialize_room_interactions")]
  public static extern void serialize_room_interactions(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_ThrowManagedException")]
  public static extern void ThrowManagedException(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_Cstretch_blit")]
  public static extern void Cstretch_blit(HandleRef jarg1, HandleRef jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, int jarg9, int jarg10);

  [DllImport("acswig", EntryPoint="CSharp_Cstretch_sprite")]
  public static extern void Cstretch_sprite(HandleRef jarg1, HandleRef jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [DllImport("acswig", EntryPoint="CSharp_reload_font")]
  public static extern bool reload_font(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_drawBlockScaledAt")]
  public static extern void drawBlockScaledAt(int jarg1, HandleRef jarg2, int jarg3, int jarg4, int jarg5);

  [DllImport("acswig", EntryPoint="CSharp_write_log")]
  public static extern void write_log(string jarg1);

  [DllImport("acswig", EntryPoint="CSharp_initialize_native")]
  public static extern bool initialize_native();

  [DllImport("acswig", EntryPoint="CSharp_update_font_sizes")]
  public static extern void update_font_sizes();

  [DllImport("acswig", EntryPoint="CSharp_copy_global_palette_to_room_palette")]
  public static extern void copy_global_palette_to_room_palette();

  [DllImport("acswig", EntryPoint="CSharp_reset_sprite_file")]
  public static extern bool reset_sprite_file();

  [DllImport("acswig", EntryPoint="CSharp_get_bitmap_for_mask")]
  public static extern IntPtr get_bitmap_for_mask(HandleRef jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_validate_mask")]
  public static extern void validate_mask(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("acswig", EntryPoint="CSharp_set_rgb_mask_from_alpha_channel")]
  public static extern void set_rgb_mask_from_alpha_channel(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_set_opaque_alpha_channel")]
  public static extern void set_opaque_alpha_channel(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_fix_block")]
  public static extern void fix_block(HandleRef jarg1);

  [DllImport("acswig", EntryPoint="CSharp_sort_out_transparency")]
  public static extern void sort_out_transparency(HandleRef jarg1, int jarg2, HandleRef jarg3, bool jarg4, int jarg5);

  [DllImport("acswig", EntryPoint="CSharp_SetNewSprite")]
  public static extern void SetNewSprite(int jarg1, HandleRef jarg2);

  [DllImport("acswig", EntryPoint="CSharp_get_sprite")]
  public static extern IntPtr get_sprite(int jarg1);

  [DllImport("acswig", EntryPoint="CSharp_cast_to_roomstruct")]
  public static extern IntPtr cast_to_roomstruct(IntPtr jarg1);

  [DllImport("acswig", EntryPoint="CSharp_get_bitmap_for_mask_from_void")]
  public static extern IntPtr get_bitmap_for_mask_from_void(IntPtr jarg1, int jarg2);

  [DllImport("acswig", EntryPoint="CSharp_GameSetupStruct_SWIGUpcast")]
  public static extern IntPtr GameSetupStruct_SWIGUpcast(IntPtr jarg1);
}
