/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class NativeViewFrame : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NativeViewFrame(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(NativeViewFrame obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~NativeViewFrame() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          acswigPINVOKE.delete_NativeViewFrame(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int pic {
    set {
      acswigPINVOKE.NativeViewFrame_pic_set(swigCPtr, value);
    } 
    get {
      int ret = acswigPINVOKE.NativeViewFrame_pic_get(swigCPtr);
      return ret;
    } 
  }

  public short xoffs {
    set {
      acswigPINVOKE.NativeViewFrame_xoffs_set(swigCPtr, value);
    } 
    get {
      short ret = acswigPINVOKE.NativeViewFrame_xoffs_get(swigCPtr);
      return ret;
    } 
  }

  public short yoffs {
    set {
      acswigPINVOKE.NativeViewFrame_yoffs_set(swigCPtr, value);
    } 
    get {
      short ret = acswigPINVOKE.NativeViewFrame_yoffs_get(swigCPtr);
      return ret;
    } 
  }

  public short speed {
    set {
      acswigPINVOKE.NativeViewFrame_speed_set(swigCPtr, value);
    } 
    get {
      short ret = acswigPINVOKE.NativeViewFrame_speed_get(swigCPtr);
      return ret;
    } 
  }

  public int flags {
    set {
      acswigPINVOKE.NativeViewFrame_flags_set(swigCPtr, value);
    } 
    get {
      int ret = acswigPINVOKE.NativeViewFrame_flags_get(swigCPtr);
      return ret;
    } 
  }

  public int sound {
    set {
      acswigPINVOKE.NativeViewFrame_sound_set(swigCPtr, value);
    } 
    get {
      int ret = acswigPINVOKE.NativeViewFrame_sound_get(swigCPtr);
      return ret;
    } 
  }

  public NativeViewFrame() : this(acswigPINVOKE.new_NativeViewFrame(), true) {
  }

}
