/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class NativeViewFrameArray : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NativeViewFrameArray(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(NativeViewFrameArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~NativeViewFrameArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          acswigPINVOKE.delete_NativeViewFrameArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public NativeViewFrameArray(int nelements) : this(acswigPINVOKE.new_NativeViewFrameArray(nelements), true) {
  }

  public NativeViewFrame getitem(int index) {
    NativeViewFrame ret = new NativeViewFrame(acswigPINVOKE.NativeViewFrameArray_getitem(swigCPtr, index), true);
    return ret;
  }

  public void setitem(int index, NativeViewFrame value) {
    acswigPINVOKE.NativeViewFrameArray_setitem(swigCPtr, index, NativeViewFrame.getCPtr(value));
    if (acswigPINVOKE.SWIGPendingException.Pending) throw acswigPINVOKE.SWIGPendingException.Retrieve();
  }

  public NativeViewFrame cast() {
    IntPtr cPtr = acswigPINVOKE.NativeViewFrameArray_cast(swigCPtr);
    NativeViewFrame ret = (cPtr == IntPtr.Zero) ? null : new NativeViewFrame(cPtr, false);
    return ret;
  }

  public static NativeViewFrameArray frompointer(NativeViewFrame t) {
    IntPtr cPtr = acswigPINVOKE.NativeViewFrameArray_frompointer(NativeViewFrame.getCPtr(t));
    NativeViewFrameArray ret = (cPtr == IntPtr.Zero) ? null : new NativeViewFrameArray(cPtr, false);
    return ret;
  }

}
