/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class RGB : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RGB(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RGB obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RGB() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          acswigPINVOKE.delete_RGB(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public byte r {
    set {
      acswigPINVOKE.RGB_r_set(swigCPtr, value);
    } 
    get {
      byte ret = acswigPINVOKE.RGB_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      acswigPINVOKE.RGB_g_set(swigCPtr, value);
    } 
    get {
      byte ret = acswigPINVOKE.RGB_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte b {
    set {
      acswigPINVOKE.RGB_b_set(swigCPtr, value);
    } 
    get {
      byte ret = acswigPINVOKE.RGB_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte filler {
    set {
      acswigPINVOKE.RGB_filler_set(swigCPtr, value);
    } 
    get {
      byte ret = acswigPINVOKE.RGB_filler_get(swigCPtr);
      return ret;
    } 
  }

  public RGB() : this(acswigPINVOKE.new_RGB(), true) {
  }

}
